export const CHOOSE_BALL_SHAPE_START = 'CHOOSE_BALL_SHAPE_START';
export const CHOOSE_BALL_SHAPE_DONE = 'CHOOSE_BALL_SHAPE_DONE';
export const CHOOSE_BALL_SHAPE_ERROR = 'CHOOSE_BALL_SHAPE_ERROR';
export const CHOOSE_BALL_SPEED_START = 'CHOOSE_BALL_SPEED_START';
export const CHOOSE_BALL_SPEED_DONE = 'CHOOSE_BALL_SPEED_DONE';
export const CHOOSE_BALL_SPEED_ERROR = 'CHOOSE_BALL_SPEED_ERROR';
export const CHOOSE_BALL_DIRECTION_START = 'CHOOSE_BALL_DIRECTION_START';
export const CHOOSE_BALL_DIRECTION_DONE = 'CHOOSE_BALL_DIRECTION_DONE';
export const CHOOSE_BALL_DIRECTION_ERROR = 'CHOOSE_BALL_DIRECTION_ERROR';


export const SESSION_CREATE_START = "SESSION_CREATE_START"
export const SESSION_CREATE_DONE = "SESSION_CREATE_DONE"
export const SESSION_CREATE_ERROR = "SESSION_CREATE_ERROR"

export const GET_SESSION_INFO_START = "GET_SESSION_INFO_START"
export const GET_SESSION_INFO_DONE = "GET_SESSION_INFO_DONE"
export const GET_SESSION_INFO_ERROR = "GET_SESSION_INFO_ERROR"

export const SERVER_URL = "http://localhost:5050"