export const CHOOSE_BALL_SHAPE_START = 'CHOOSE_BALL_SHAPE_START';
export const CHOOSE_BALL_SHAPE_DONE = 'CHOOSE_BALL_SHAPE_DONE';
export const CHOOSE_BALL_SHAPE_ERROR = 'CHOOSE_BALL_SHAPE_ERROR';
export const CHOOSE_BALL_SPEED_START = 'CHOOSE_BALL_SPEED_START';
export const CHOOSE_BALL_SPEED_DONE = 'CHOOSE_BALL_SPEED_DONE';
export const CHOOSE_BALL_SPEED_ERROR = 'CHOOSE_BALL_SPEED_ERROR';
export const CHOOSE_BALL_DIRECTION_START = 'CHOOSE_BALL_DIRECTION_START';
export const CHOOSE_BALL_DIRECTION_DONE = 'CHOOSE_BALL_DIRECTION_DONE';
export const CHOOSE_BALL_DIRECTION_ERROR = 'CHOOSE_BALL_DIRECTION_ERROR';


export const SESSION_CREATE = "SESSION_CREATE"
export const SESSION_CREATE_START = "SESSION_CREATE_START"
export const SESSION_CREATE_DONE = "SESSION_CREATE_DONE"
export const SESSION_CREATE_ERROR = "SESSION_CREATE_ERROR"

export const GET_SESSION_INFO = "GET_SESSION_INFO"
export const GET_SESSION_INFO_FROM_SESSION = "GET_SESSION_INFO_FROM_SESSION"
export const GET_SESSION_INFO_START = "GET_SESSION_INFO_START"
export const GET_SESSION_INFO_DONE = "GET_SESSION_INFO_DONE"
export const GET_SESSION_INFO_ERROR = "GET_SESSION_INFO_ERROR"
export const GET_SESSION_INFO_NOSOUND = "GET_SESSION_INFO_NOSOUND"
export const GET_SESSION_INFO_NOSOUND_START = "GET_SESSION_INFO_NOSOUND_START"
export const GET_SESSION_INFO_NOSOUND_DONE = "GET_SESSION_INFO_NOSOUND_DONE"
export const GET_SESSION_INFO_NOSOUND_ERROR = "GET_SESSION_INFO_NOSOUND_ERROR"

export const UPDATE_SESSION = "UPDATE_SESSION"
export const UPDATE_SESSION_START = "UPDATE_SESSION_START"
export const UPDATE_SESSION_DONE = "UPDATE_SESSION_DONE"
export const UPDATE_SESSION_ERROR = "UPDATE_SESSION_ERROR"

export const UPDATE_SESSION_WITH_SOCKET = "UPDATE_SESSION_WITH_SOCKET"
export const UPDATE_SESSION_WITH_SOCKET_START = "UPDATE_SESSION_WITH_SOCKET_START"
export const UPDATE_SESSION_WITH_SOCKET_DONE = "UPDATE_SESSION_WITH_SOCKET_DONE"
export const UPDATE_SESSION_WITH_SOCKET_ERROR = "UPDATE_SESSION_WITH_SOCKET_ERROR"

export const DELETE_SESSION_START = "DELETE_SESSION_START"
export const DELETE_SESSION_DONE = "DELETE_SESSION_DONE"
export const DELETE_SESSION_ERROR = "DELETE_SESSION_ERROR"

export const UPDATE_BALL_SPEED = "UPDATE_BALL_SPEED"
export const START_STOP_ACTION = "START_STOP_ACTION"
export const SET_SOUND_ACTION = "SET_SOUND_ACTION"
export const SET_SHAPE_ACTION = "SET_SHAPE_ACTION"

// export const SERVER_URL = "http://3.123.80.140"
export const SERVER_URL = "http://localhost:5050"
// export const SERVER_URL_SOCKET = "http://3.123.80.140"
export const SERVER_URL_SOCKET = "http://localhost:5050"
